"""The third-party licence gate in `scripts/third_party_notices.py`.

The notices file is regenerated by hand and verified in CI, so the part that
actually protects anything is the classifier: if it silently called a GPL
dependency permissive, `--check` would pass a release that should have stopped.
These tests pin that behaviour, plus the two closure rules that decide *which*
packages get a notice at all.

The script lives outside the package (it is tooling, not shipped code), so it is
loaded by path rather than imported.
"""

from __future__ import annotations

import importlib.util
import sys
import tomllib
from pathlib import Path

import pytest

_SCRIPT = Path(__file__).resolve().parent.parent / "scripts" / "third_party_notices.py"
_spec = importlib.util.spec_from_file_location("third_party_notices", _SCRIPT)
assert _spec is not None and _spec.loader is not None
notices = importlib.util.module_from_spec(_spec)
sys.modules["third_party_notices"] = notices
_spec.loader.exec_module(notices)

LOCK = tomllib.loads(notices.LOCK_PATH.read_text(encoding="utf-8"))
DEFINED_EXTRAS = notices.image_closure_extras(LOCK)


def image_extras() -> frozenset[str]:
    """What the repo's own Dockerfile installs, resolved the way the script does."""
    return notices.dockerfile_extras(DEFINED_EXTRAS)


@pytest.mark.parametrize(
    ("expression", "verdict"),
    [
        # SPDX ids and the classifier spellings of the same licences.
        ("MIT", "permissive"),
        ("BSD License", "permissive"),
        ("Apache Software License", "permissive"),
        ("ISC License (ISCL)", "permissive"),
        ("PSF-2.0", "permissive"),
        ("MIT-CMU", "permissive"),
        # A choice of permissive licences is still permissive.
        ("MIT OR Apache-2.0", "permissive"),
        # Copyleft, in both spellings.
        ("GPL-3.0-only", "strong-copyleft"),
        ("GNU General Public License v2 or later (GPLv2+)", "strong-copyleft"),
        ("AGPL-3.0", "strong-copyleft"),
        ("LGPL-2.1-or-later", "weak-copyleft"),
        ("MPL-2.0", "weak-copyleft"),
        ("Mozilla Public License 2.0 (MPL 2.0)", "weak-copyleft"),
        # pyphen's tri-licence: the GPL option is present, so it escalates.
        ("GPLv2+ OR LGPLv2.1+ OR MPL-1.1", "strong-copyleft"),
        # Anything unrecognised must escalate rather than be assumed benign.
        ("Proprietary", "unknown"),
        ("", "unknown"),
    ],
)
def test_classify(expression: str, verdict: str) -> None:
    assert notices.classify(expression) == verdict


def test_lgpl_is_not_mistaken_for_gpl() -> None:
    """`^GPL` would match LGPL as a substring — the distinction is the whole point."""
    assert notices.classify("LGPL-3.0") == "weak-copyleft"


def _package(name: str, expression: str, *, in_image: bool = True) -> notices.Package:
    return notices.Package(
        name=name,
        version="1.0",
        license_expression=expression,
        verdict=notices.classify(expression),
        texts=(("LICENSE", "..."),),
        in_image=in_image,
    )


def test_policy_passes_permissive_dependencies() -> None:
    assert notices.enforce_policy([_package("httpx", "BSD-3-Clause")]) == []


def test_policy_fails_a_new_copyleft_dependency() -> None:
    failures = notices.enforce_policy([_package("some-new-dep", "GPL-3.0-only")])
    assert len(failures) == 1
    assert "some-new-dep" in failures[0]
    assert "ACKNOWLEDGED" in failures[0]


def test_policy_fails_an_undeclared_licence() -> None:
    assert notices.enforce_policy([_package("mystery", "")])


def test_policy_allows_an_acknowledged_dependency() -> None:
    """pyphen is copyleft and stays — because someone wrote down why."""
    assert "pyphen" in notices.ACKNOWLEDGED
    approved = notices.ACKNOWLEDGED["pyphen"].license_expression
    assert notices.classify(approved) == "strong-copyleft"
    assert notices.enforce_policy([_package("pyphen", approved)]) == []


def test_markers_are_resolved_for_the_published_platform() -> None:
    assert notices.marker_applies(None)
    assert notices.marker_applies("python_full_version < '3.13'")  # true on 3.12
    assert notices.marker_applies("platform_python_implementation == 'CPython'")
    assert not notices.marker_applies("sys_platform == 'win32'")
    assert not notices.marker_applies("platform_python_implementation != 'CPython'")


def test_closure_is_what_we_ship_and_nothing_else() -> None:
    """Runtime + arrow + pdf get notices; build-time tooling does not."""
    import tomllib

    lock = tomllib.loads(notices.LOCK_PATH.read_text(encoding="utf-8"))
    closure = notices.distributed_closure(lock, notices.NOTICED_EXTRAS)

    for shipped in ("httpx", "pydantic", "typer", "pyarrow", "weasyprint", "pyphen"):
        assert shipped in closure, f"{shipped} is redistributed but has no notice"
    for tooling in ("pytest", "ruff", "mypy", "respx", "packaging"):
        assert tooling not in closure, f"{tooling} is a dev tool, not a shipped work"
    # Excluded by marker: no published artifact is Windows or PyPy.
    assert "colorama" not in closure
    assert "brotlicffi" not in closure


def test_aliases_cannot_rewrite_their_own_output() -> None:
    """An alias whose key appears in its value would corrupt the text it just fixed.

    (`"APACHE-2" -> "APACHE-2.0"` turned a correct expression into `APACHE-2.0.0`.)
    """
    for phrase, token in notices.LICENSE_ALIASES.items():
        assert phrase not in token, f"alias {phrase!r} -> {token!r} is self-applying"


def test_platform_notice_tracks_the_dockerfile() -> None:
    """The platform section names the interpreter version and its license path.

    Both are read from the Dockerfile rather than written down, so a base-image
    bump cannot leave the notice claiming a version the image no longer has.
    """
    image, python_version = notices.runtime_base_image()
    assert image.startswith("python:")
    assert image.endswith("-slim")
    assert python_version in image
    assert f"FROM {image} AS runtime" in notices.DOCKERFILE_PATH.read_text(encoding="utf-8")

    rendered = notices.PLATFORM_SECTION.replace("{{IMAGE}}", image).replace(
        "{{PYVER}}", python_version
    )
    assert f"FROM {image}" in rendered
    assert f"/usr/local/lib/python{python_version}/LICENSE.txt" in rendered
    assert "{{" not in rendered, "an unreplaced placeholder is left in the notice"


def test_the_election_matches_what_the_image_ships() -> None:
    """The image installs the `pdf` extra, so the choice of pyphen licence is ours.

    Both halves are asserted together on purpose: an election recorded while
    nothing ships pyphen would be an unnecessary commitment, and shipping it
    without one would distribute a GPL-optional package with no record of which
    option was taken. Whichever way the Dockerfile goes, these move together.
    """
    ships_pdf = "pdf" in image_extras()
    assert ships_pdf
    assert notices.PYPHEN_ELECTION == "LGPL-2.1-or-later"
    assert notices.enforce_pyphen_election(ships_pdf, notices.PYPHEN_ELECTION) == []

    note = notices.ACKNOWLEDGED["pyphen"].note
    assert "elects LGPL-2.1-or-later" in note
    assert "does not accept the GPL option" in note


def test_shipping_the_pdf_extra_forces_the_election() -> None:
    """The moment an artifact bundles pyphen, the choice has to be recorded."""
    failures = notices.enforce_pyphen_election(ships_pdf=True, election=None)
    assert len(failures) == 1
    assert "PYPHEN_ELECTION" in failures[0]


def test_a_recorded_election_satisfies_the_guard() -> None:
    assert notices.enforce_pyphen_election(ships_pdf=True, election="LGPL-2.1-or-later") == []


def test_acknowledgement_is_bound_to_the_licence_that_was_reviewed() -> None:
    """Relicensing must re-enter the gate, not inherit approval granted to old terms."""
    approved = notices.ACKNOWLEDGED["certifi"].license_expression
    assert notices.enforce_policy([_package("certifi", approved)]) == []

    failures = notices.enforce_policy([_package("certifi", "GPL-3.0-only")])
    assert len(failures) == 1
    assert "acknowledged under" in failures[0]
    assert "GPL-3.0-only" in failures[0]


def test_every_acknowledgement_matches_what_the_closure_declares() -> None:
    """The approved expressions must be the live ones, or the gate is already stale."""
    import tomllib

    lock = tomllib.loads(notices.LOCK_PATH.read_text(encoding="utf-8"))
    packages = {p.name: p for p in notices.collect(lock, image_extras())}
    for name, acknowledgement in notices.ACKNOWLEDGED.items():
        assert packages[name].license_expression == acknowledgement.license_expression


@pytest.mark.parametrize(
    "run_line",
    [
        "RUN uv sync --frozen --no-dev --extra arrow --extra pdf",
        "RUN uv sync --frozen --extra=pdf",
        "RUN uv sync --frozen --no-dev \\\n    --extra arrow \\\n    --extra pdf",
        "RUN --mount=type=cache,target=/root/.cache/uv \\\n    uv sync --extra pdf",
    ],
)
def test_dockerfile_extras_survives_reformatting(
    run_line: str, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A guard that a line continuation defeats is worse than no guard."""
    dockerfile = tmp_path / "Dockerfile"
    dockerfile.write_text(f"FROM python:3.14-slim AS runtime\n{run_line}\n")
    monkeypatch.setattr(notices, "DOCKERFILE_PATH", dockerfile)
    assert "pdf" in notices.dockerfile_extras(DEFINED_EXTRAS)


def test_dockerfile_extras_ignores_comments(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Prose about `uv sync --extra pdf` is not an installation of it."""
    dockerfile = tmp_path / "Dockerfile"
    dockerfile.write_text(
        "# PDF stays out; adding it would mean `uv sync --extra pdf` here.\n"
        "RUN uv sync --frozen --extra arrow\n"
    )
    monkeypatch.setattr(notices, "DOCKERFILE_PATH", dockerfile)
    assert notices.dockerfile_extras(DEFINED_EXTRAS) == frozenset({"arrow"})


def test_the_image_column_reflects_what_the_dockerfile_installs() -> None:
    """The column tracks the Dockerfile's extras, not the whole noticed closure."""
    import tomllib

    lock = tomllib.loads(notices.LOCK_PATH.read_text(encoding="utf-8"))
    packages = {p.name: p for p in notices.collect(lock, image_extras())}
    # The image installs both extras today, so everything credited is shipped.
    for shipped in ("pyarrow", "weasyprint", "pyphen", "pillow", "webencodings"):
        assert packages[shipped].in_image, f"{shipped} is installed by the Dockerfile"

    # Drop an extra and the split reappears — this is the mechanism, not the
    # current configuration, and it is what keeps the column honest if the
    # Dockerfile ever narrows again.
    arrow_only = notices.distributed_closure(lock, ["arrow"])
    assert "pyarrow" in arrow_only
    for pdf_only in ("weasyprint", "pyphen", "pillow", "webencodings"):
        assert pdf_only not in arrow_only


def test_the_image_can_actually_run_what_it_installs() -> None:
    """Shipping WeasyPrint without Pango yields an image that fails at render time.

    The wheel installs cleanly with no system libraries, so nothing before this
    point would notice: the failure only shows up when a spec asks for PDF.
    """
    dockerfile = notices.DOCKERFILE_PATH.read_text(encoding="utf-8")
    if "pdf" in image_extras():
        assert "libpango-1.0-0" in dockerfile, "WeasyPrint draws through Pango"
        assert "fonts-" in dockerfile, "with no font installed, text renders as boxes"


def _extras_for(content: str, tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> frozenset[str]:
    dockerfile = tmp_path / "Dockerfile"
    dockerfile.write_text(content)
    monkeypatch.setattr(notices, "DOCKERFILE_PATH", dockerfile)
    return notices.dockerfile_extras(DEFINED_EXTRAS)


def test_all_extras_is_expanded_not_ignored(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """`--all-extras` installs everything, so it must not read as installing nothing.

    An unrecognised flag here fails silently in the worst direction: every package
    would be marked as not redistributed and the pyphen election skipped, while the
    notice still reads as though it had checked.
    """
    extras = _extras_for("RUN uv sync --frozen --no-dev --all-extras\n", tmp_path, monkeypatch)
    assert extras == frozenset(DEFINED_EXTRAS)
    assert "pdf" in extras, "pyphen would ship without an election"


def test_all_extras_honours_no_extra(tmp_path: Path, monkeypatch: pytest.MonkeyPatch) -> None:
    extras = _extras_for("RUN uv sync --all-extras --no-extra dev\n", tmp_path, monkeypatch)
    assert extras == frozenset({"arrow", "pdf"})


def test_no_extra_is_not_mistaken_for_extra(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """`--no-extra pdf` excludes pdf; a looser pattern would read it as adding it."""
    extras = _extras_for("RUN uv sync --extra arrow --no-extra pdf\n", tmp_path, monkeypatch)
    assert extras == frozenset({"arrow"})


def test_expanding_all_extras_surfaces_an_unaccounted_extra() -> None:
    """`--all-extras` sweeps in `dev`, which the notice does not cover — so it fails."""
    with pytest.raises(SystemExit, match="does not account for"):
        notices.collect(LOCK, frozenset(DEFINED_EXTRAS))


def test_an_unreadable_installer_is_refused_not_ignored(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Switching install tooling must stop the build, not empty out the notice."""
    with pytest.raises(SystemExit, match="cannot read extras from"):
        _extras_for("RUN pip install '.[pdf]'\n", tmp_path, monkeypatch)
