"""The third-party licence gate in `scripts/third_party_notices.py`.

The notices file is regenerated by hand and verified in CI, so the part that
actually protects anything is the classifier: if it silently called a GPL
dependency permissive, `--check` would pass a release that should have stopped.
These tests pin that behaviour, plus the two closure rules that decide *which*
packages get a notice at all.

The script lives outside the package (it is tooling, not shipped code), so it is
loaded by path rather than imported.
"""

from __future__ import annotations

import importlib.util
import sys
from pathlib import Path

import pytest

_SCRIPT = Path(__file__).resolve().parent.parent / "scripts" / "third_party_notices.py"
_spec = importlib.util.spec_from_file_location("third_party_notices", _SCRIPT)
assert _spec is not None and _spec.loader is not None
notices = importlib.util.module_from_spec(_spec)
sys.modules["third_party_notices"] = notices
_spec.loader.exec_module(notices)


@pytest.mark.parametrize(
    ("expression", "verdict"),
    [
        # SPDX ids and the classifier spellings of the same licences.
        ("MIT", "permissive"),
        ("BSD License", "permissive"),
        ("Apache Software License", "permissive"),
        ("ISC License (ISCL)", "permissive"),
        ("PSF-2.0", "permissive"),
        ("MIT-CMU", "permissive"),
        # A choice of permissive licences is still permissive.
        ("MIT OR Apache-2.0", "permissive"),
        # Copyleft, in both spellings.
        ("GPL-3.0-only", "strong-copyleft"),
        ("GNU General Public License v2 or later (GPLv2+)", "strong-copyleft"),
        ("AGPL-3.0", "strong-copyleft"),
        ("LGPL-2.1-or-later", "weak-copyleft"),
        ("MPL-2.0", "weak-copyleft"),
        ("Mozilla Public License 2.0 (MPL 2.0)", "weak-copyleft"),
        # pyphen's tri-licence: the GPL option is present, so it escalates.
        ("GPLv2+ OR LGPLv2.1+ OR MPL-1.1", "strong-copyleft"),
        # Anything unrecognised must escalate rather than be assumed benign.
        ("Proprietary", "unknown"),
        ("", "unknown"),
    ],
)
def test_classify(expression: str, verdict: str) -> None:
    assert notices.classify(expression) == verdict


def test_lgpl_is_not_mistaken_for_gpl() -> None:
    """`^GPL` would match LGPL as a substring — the distinction is the whole point."""
    assert notices.classify("LGPL-3.0") == "weak-copyleft"


def _package(name: str, expression: str, *, in_image: bool = True) -> notices.Package:
    return notices.Package(
        name=name,
        version="1.0",
        license_expression=expression,
        verdict=notices.classify(expression),
        texts=(("LICENSE", "..."),),
        in_image=in_image,
    )


def test_policy_passes_permissive_dependencies() -> None:
    assert notices.enforce_policy([_package("httpx", "BSD-3-Clause")]) == []


def test_policy_fails_a_new_copyleft_dependency() -> None:
    failures = notices.enforce_policy([_package("some-new-dep", "GPL-3.0-only")])
    assert len(failures) == 1
    assert "some-new-dep" in failures[0]
    assert "ACKNOWLEDGED" in failures[0]


def test_policy_fails_an_undeclared_licence() -> None:
    assert notices.enforce_policy([_package("mystery", "")])


def test_policy_allows_an_acknowledged_dependency() -> None:
    """pyphen is copyleft and stays — because someone wrote down why."""
    assert "pyphen" in notices.ACKNOWLEDGED
    approved = notices.ACKNOWLEDGED["pyphen"].license_expression
    assert notices.classify(approved) == "strong-copyleft"
    assert notices.enforce_policy([_package("pyphen", approved)]) == []


def test_markers_are_resolved_for_the_published_platform() -> None:
    assert notices.marker_applies(None)
    assert notices.marker_applies("python_full_version < '3.13'")  # true on 3.12
    assert notices.marker_applies("platform_python_implementation == 'CPython'")
    assert not notices.marker_applies("sys_platform == 'win32'")
    assert not notices.marker_applies("platform_python_implementation != 'CPython'")


def test_closure_is_what_we_ship_and_nothing_else() -> None:
    """Runtime + arrow + pdf get notices; build-time tooling does not."""
    import tomllib

    lock = tomllib.loads(notices.LOCK_PATH.read_text(encoding="utf-8"))
    closure = notices.distributed_closure(lock, notices.NOTICED_EXTRAS)

    for shipped in ("httpx", "pydantic", "typer", "pyarrow", "weasyprint", "pyphen"):
        assert shipped in closure, f"{shipped} is redistributed but has no notice"
    for tooling in ("pytest", "ruff", "mypy", "respx", "packaging"):
        assert tooling not in closure, f"{tooling} is a dev tool, not a shipped work"
    # Excluded by marker: no published artifact is Windows or PyPy.
    assert "colorama" not in closure
    assert "brotlicffi" not in closure


def test_aliases_cannot_rewrite_their_own_output() -> None:
    """An alias whose key appears in its value would corrupt the text it just fixed.

    (`"APACHE-2" -> "APACHE-2.0"` turned a correct expression into `APACHE-2.0.0`.)
    """
    for phrase, token in notices.LICENSE_ALIASES.items():
        assert phrase not in token, f"alias {phrase!r} -> {token!r} is self-applying"


def test_platform_notice_tracks_the_dockerfile() -> None:
    """The platform section names the interpreter version and its license path.

    Both are read from the Dockerfile rather than written down, so a base-image
    bump cannot leave the notice claiming a version the image no longer has.
    """
    image, python_version = notices.runtime_base_image()
    assert image.startswith("python:")
    assert image.endswith("-slim")
    assert python_version in image
    assert f"FROM {image} AS runtime" in notices.DOCKERFILE_PATH.read_text(encoding="utf-8")

    rendered = notices.PLATFORM_SECTION.replace("{{IMAGE}}", image).replace(
        "{{PYVER}}", python_version
    )
    assert f"FROM {image}" in rendered
    assert f"/usr/local/lib/python{python_version}/LICENSE.txt" in rendered
    assert "{{" not in rendered, "an unreplaced placeholder is left in the notice"


def test_no_pyphen_election_is_needed_while_nothing_ships_it() -> None:
    """Today's state: the image is `--extra arrow`, so pyphen is never ours to license."""
    assert "pdf" not in notices.dockerfile_extras()
    assert notices.PYPHEN_ELECTION is None
    assert notices.enforce_pyphen_election(ships_pdf=False, election=None) == []
    assert "No election has been made" in notices.ACKNOWLEDGED["pyphen"].note


def test_shipping_the_pdf_extra_forces_the_election() -> None:
    """The moment an artifact bundles pyphen, the choice has to be recorded."""
    failures = notices.enforce_pyphen_election(ships_pdf=True, election=None)
    assert len(failures) == 1
    assert "PYPHEN_ELECTION" in failures[0]


def test_a_recorded_election_satisfies_the_guard() -> None:
    assert notices.enforce_pyphen_election(ships_pdf=True, election="LGPL-2.1-or-later") == []


def test_acknowledgement_is_bound_to_the_licence_that_was_reviewed() -> None:
    """Relicensing must re-enter the gate, not inherit approval granted to old terms."""
    approved = notices.ACKNOWLEDGED["certifi"].license_expression
    assert notices.enforce_policy([_package("certifi", approved)]) == []

    failures = notices.enforce_policy([_package("certifi", "GPL-3.0-only")])
    assert len(failures) == 1
    assert "acknowledged under" in failures[0]
    assert "GPL-3.0-only" in failures[0]


def test_every_acknowledgement_matches_what_the_closure_declares() -> None:
    """The approved expressions must be the live ones, or the gate is already stale."""
    import tomllib

    lock = tomllib.loads(notices.LOCK_PATH.read_text(encoding="utf-8"))
    packages = {p.name: p for p in notices.collect(lock, notices.dockerfile_extras())}
    for name, acknowledgement in notices.ACKNOWLEDGED.items():
        assert packages[name].license_expression == acknowledgement.license_expression


@pytest.mark.parametrize(
    "run_line",
    [
        "RUN uv sync --frozen --no-dev --extra arrow --extra pdf",
        "RUN uv sync --frozen --extra=pdf",
        "RUN uv sync --frozen --no-dev \\\n    --extra arrow \\\n    --extra pdf",
        "RUN --mount=type=cache,target=/root/.cache/uv \\\n    uv sync --extra pdf",
    ],
)
def test_dockerfile_extras_survives_reformatting(
    run_line: str, tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """A guard that a line continuation defeats is worse than no guard."""
    dockerfile = tmp_path / "Dockerfile"
    dockerfile.write_text(f"FROM python:3.14-slim AS runtime\n{run_line}\n")
    monkeypatch.setattr(notices, "DOCKERFILE_PATH", dockerfile)
    assert "pdf" in notices.dockerfile_extras()


def test_dockerfile_extras_ignores_comments(
    tmp_path: Path, monkeypatch: pytest.MonkeyPatch
) -> None:
    """Prose about `uv sync --extra pdf` is not an installation of it."""
    dockerfile = tmp_path / "Dockerfile"
    dockerfile.write_text(
        "# PDF stays out; adding it would mean `uv sync --extra pdf` here.\n"
        "RUN uv sync --frozen --extra arrow\n"
    )
    monkeypatch.setattr(notices, "DOCKERFILE_PATH", dockerfile)
    assert notices.dockerfile_extras() == frozenset({"arrow"})


def test_the_image_column_reflects_what_the_dockerfile_installs() -> None:
    """`pdf`-only packages are credited but must not be claimed as redistributed."""
    import tomllib

    lock = tomllib.loads(notices.LOCK_PATH.read_text(encoding="utf-8"))
    packages = {p.name: p for p in notices.collect(lock, notices.dockerfile_extras())}
    assert packages["pyarrow"].in_image, "the image is built --extra arrow"
    for pdf_only in ("pyphen", "weasyprint", "pillow", "webencodings"):
        assert not packages[pdf_only].in_image, f"{pdf_only} is not in the image"
